const { BirthChartService, VimshottariDashaService, PrashnaAstrologyService, EventAstrologyService, MuhurtaService, SolarArcDirectionsService, SecondaryProgressionsService, SolarReturnService, BusinessPartnershipService, SpecializedAnalysisService, DashaPredictiveService, CalendarTimingService, CurrentDashaService, CurrentTransitsService, DailyHoroscopeService, CompatibilityService, DetailedChartAnalysisService, CompatibilityScoreService, PanchangService, AshtakavargaService, DavisonChartService, LunarReturnService, AdvancedCompatibilityService, EnhancedPanchangService, PrashnaService, JaiminiAstrologyService, GocharService, VarshaphalService, JaiminiDashasService, AdvancedTransitsService, MajorTransitsService, TransitPreviewService, AsteroidsService, CoupleCompatibilityService, SynastryAnalysisService, HinduFestivalsService, NumerologyAnalysisService, HoraryReadingService, ComprehensiveVedicAnalysisService, FutureSelfSimulatorService, LifePatternsService, FinancialAstrologyService, NumerologyReportService, FixedStarsService, CareerAstrologyService, AbhijitMuhurtaService, RahukalamService, GulikakalamService, KaalSarpDoshaService, SadeSatiService, MedicalAstrologyService, NadiAstrologyService } = require('./vedic');
const { WesternAstrologyService } = require('./western');
const { DivinationService, NumerologyService, TarotReadingService } = require('./common');

module.exports = {
  BirthChartService,
  VimshottariDashaService,
  PrashnaAstrologyService,
  EventAstrologyService,
  MuhurtaService,
  SolarArcDirectionsService,
  SecondaryProgressionsService,
  SolarReturnService,
  BusinessPartnershipService,
  SpecializedAnalysisService,
  DashaPredictiveService,
  CalendarTimingService,
  CurrentDashaService,
  CurrentTransitsService,
  DailyHoroscopeService,
  CompatibilityService,
  DetailedChartAnalysisService,
  CompatibilityScoreService,
  PanchangService,
  AshtakavargaService,
  DavisonChartService,
  LunarReturnService,
  AdvancedCompatibilityService,
  EnhancedPanchangService,
  PrashnaService,
  JaiminiAstrologyService,
  GocharService,
  VarshaphalService,
  JaiminiDashasService,
  AdvancedTransitsService,
  MajorTransitsService,
  TransitPreviewService,
  AsteroidsService,
  // HIGH PRIORITY - Newly implemented core services
  CoupleCompatibilityService,
  SynastryAnalysisService,
  HinduFestivalsService,
  NumerologyAnalysisService,
  HoraryReadingService,
  // New service implementation
  ComprehensiveVedicAnalysisService,
  FutureSelfSimulatorService,
  LifePatternsService,
  FinancialAstrologyService,
  NumerologyReportService,
  FixedStarsService,
  CareerAstrologyService,
  AbhijitMuhurtaService,
  RahukalamService,
  GulikakalamService,
  KaalSarpDoshaService,
  SadeSatiService,
  MedicalAstrologyService,
  NadiAstrologyService,
  WesternAstrologyService,
  DivinationService,
  NumerologyService,
  TarotReadingService,
};
