const { BirthChartService, VimshottariDashaService, PrashnaAstrologyService, EventAstrologyService, MuhurtaService, SolarArcDirectionsService, SecondaryProgressionsService, SolarReturnService, BusinessPartnershipService, SpecializedAnalysisService, DashaPredictiveService, CalendarTimingService, CurrentDashaService, CurrentTransitsService, DailyHoroscopeService, CompatibilityService, DetailedChartAnalysisService, CompatibilityScoreService, PanchangService, AshtakavargaService, DavisonChartService, LunarReturnService, AdvancedCompatibilityService, EnhancedPanchangService, PrashnaService, JaiminiAstrologyService, GocharService, VarshaphalService } = require('./vedic');
const { WesternAstrologyService } = require('./western');
const { DivinationService, NumerologyService, TarotReadingService } = require('./common');

module.exports = {
  BirthChartService,
  VimshottariDashaService,
  PrashnaAstrologyService,
  EventAstrologyService,
  MuhurtaService,
  SolarArcDirectionsService,
  SecondaryProgressionsService,
  SolarReturnService,
  BusinessPartnershipService,
  SpecializedAnalysisService,
  DashaPredictiveService,
  CalendarTimingService,
  CurrentDashaService,
  CurrentTransitsService,
  DailyHoroscopeService,
  CompatibilityService,
  DetailedChartAnalysisService,
  CompatibilityScoreService,
  PanchangService,
  AshtakavargaService,
  DavisonChartService,
  LunarReturnService,
  AdvancedCompatibilityService,
  EnhancedPanchangService,
  PrashnaService,
  JaiminiAstrologyService,
  GocharService,
  VarshaphalService,
  WesternAstrologyService,
  DivinationService,
  NumerologyService,
  TarotReadingService,
};
