# Railway Configuration for Astro WhatsApp Bot
# Project: w1
# Environment: production
# Service: w1
# Domain: https://w1-production-a9c7.up.railway.app

[build]
builder = "NIXPACKS"
buildCommand = "npm install"
sourceDirectory = "astro-whatsapp-bot"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "npm start"

# Environment configuration
[environments.production]
RAILWAY_ENVIRONMENT = "production"
RAILWAY_PROJECT_NAME = "w1"
RAILWAY_SERVICE_NAME = "w1"
RAILWAY_PUBLIC_DOMAIN = "w1-production-a9c7.up.railway.app"

# Cron job for WhatsApp token monitoring
[[cron]]
name = "whatsapp-token-monitor"
schedule = "*/30 * * * *"  # Every 30 minutes
command = "npm run check-token"
timeout = 300

# Daily health report
[[cron]]
name = "whatsapp-daily-health"
schedule = "0 9 * * *"  # 9 AM daily
command = "npm run token-manager health-report"
timeout = 600

# Weekly certification check
[[cron]]
name = "whatsapp-weekly-cert"
schedule = "0 10 * * 1"  # 10 AM every Monday
command = "npm run token-manager cert"
timeout = 900