[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Cron job for WhatsApp token monitoring
[[cron]]
name = "whatsapp-token-monitor"
schedule = "*/30 * * * *"  # Every 30 minutes
command = "npm run check-token"
timeout = 300

# Optional: Daily health report
[[cron]]
name = "whatsapp-daily-health"
schedule = "0 9 * * *"  # 9 AM daily
command = "npm run token-manager health-report"
timeout = 600